##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/pluma
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #requiered for unbuffer
    - gcc
    - git
    - gla11y
    - gobject-introspection
    - gtk-doc-tools
    - gvfs
    - iso-codes
    - libenchant-2-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtksourceview-3.0-dev
    - libpeas-dev
    - libsm-dev
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common
    - mate-desktop
    - python3-dev
    - python3-lxml
    - yelp-tools
    - gvfs-fuse
    - gvfs-backends
    - libglib2.0-bin

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - dbus-launch bash &
  - gio mount sftp://localhost/ &
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/mate-icon-theme/raw/master/mate/16x16/apps/accessories-text-editor.png; fi
